# Generated by Django 4.1.4 on 2023-08-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0002_alter_post_blog_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_blog',
            name='publish_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
