# Generated by Django 4.1.4 on 2023-08-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0003_alter_post_blog_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_user',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
