# Generated by Django 4.1.4 on 2023-08-20 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0004_alter_info_user_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info_user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='like_data',
            name='id',
        ),
        migrations.RemoveField(
            model_name='post_blog',
            name='id',
        ),
        migrations.AlterField(
            model_name='info_user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='like_data',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='like_data',
            name='like_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='like_data',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_app.post_blog'),
        ),
        migrations.AlterField(
            model_name='like_data',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_app.info_user'),
        ),
        migrations.AlterField(
            model_name='post_blog',
            name='post_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post_blog',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_app.info_user'),
        ),
    ]
