# Generated by Django 4.1.4 on 2023-08-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0005_remove_info_user_id_remove_like_data_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like_data',
            name='likes',
            field=models.IntegerField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
