# Generated by Django 4.1.4 on 2023-08-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0006_like_data_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_data',
            name='post_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='like_data',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post_blog',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
