# Generated by Django 4.1.4 on 2023-08-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0008_alter_post_blog_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='like_data',
            name='dislikes',
            field=models.IntegerField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
